name: Deploy to server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to container reigstry
        uses: docker/login-action@v3
        with:
          registry: docker.sdcmuj.com
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.sdcmuj.com/circon

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.output.labels }}
          cache-from: type=registry,ref=docker.sdcmuj.com/circon:buildcache
          cache-to: type=registry,ref=docker.sdcmuj.com/circon:buildcache,mode=max

